### ISSUE TITLE
`Package 'DotNetInit 1.0.3' has a package type 'DotnetCliTool' that is not supported by project

### ISSUE THREAD

**Issue by HamedFathi** [maartenba/dotnetcli-init#1]
Hi

When I wanted to install your package in VS2017 `Install-Package DotNetInit
` I got an error ?

`Package 'DotNetInit 1.0.3' has a package type 'DotnetCliTool' that is not supported by project 'WebApplication3'`

How to fix it ?

**Comment by maartenba** [comment]
Looks like as per https://github.com/NuGet/Home/issues/4190, tools packages need to be hand-added by editingg the `.csproj` as described in the README :-(

**Comment by HamedFathi** [comment]
@maartenba  Thanks
